
export default {
	// register

	REGISTER_SUBMIT: 'REGISTER_SUBMIT',
	REGISTER_SUBMIT_SUCCESS: 'REGISTER_SUBMIT_SUCCESS',
	REGISTER_SUBMIT_FAIL: 'REGISTER_SUBMIT_FAIL',
	ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
	ADD_USER_FAIL: 'ADD_USER_FAIL',

	// login

	SUBMITTING_LOGIN: 'SUBMITTING_LOGIN',

	LOGIN_SUBMIT:'LOGIN_SUBMIT',
	LOGIN_SUBMIT_SUCCESS:'LOGIN_SUBMIT_SUCCESS',
	LOGIN_SUBMIT_FAIL:'LOGIN_SUBMIT_FAIL',

	// post form
	POST_MESSAGE: 'POST_MESSAGE',

	// forum 
	
	PARSE_REPLY_URL_SUCCESS:'PARSE_REPLY_URL_SUCCESS',
	PARSE_REPLY_URL_FAIL:'PARSE_REPLY_URL_FAIL',

	GET_TOPIC_SUCCESS: 'GET_TOPIC_SUCCESS',
	STORE_FORUM_NAME: 'STORE_FORUM_NAME',
	STORE_FORUM_PATH: 'STORE_FORUM_PATH',

	GET_TOPIC_FAIL:	'GET_TOPIC_FAIL',
	GET_FIRST_POST_SUCCESS:'GET_FIRST_POST_SUCCESS',
	GET_FIRST_POST_FAIL:'GET_FIRST_POST_FAIL',
	// create event

	STORE_START_TIME:'STORE_START_TIME',
	STORE_END_TIME:	'STORE_END_TIME',

	STORE_START_DATE : 'STORE_START_DATE',
	STORE_END_DATE:	'STORE_END_DATE',
	STORE_PERIOD:	'STORE_PERIOD',

	SUBMIT_ATTENDING_SUCCESS:'SUBMIT_ATTENDING_SUCCESS',
	SUBMIT_ATTENDING_FAIL:'SUBMIT_ATTENDING_FAIL',

	// topic

	GET_POST_COLLECTION_SUCCESS: 'GET_POST_COLLECTION_SUCCESS',
	GET_POST_COLLECTION_FAIL: 'GET_POST_COLLECTION_FAIL',
	UPDATE_POST_COLLECTION: 'UPDATE_POST_COLLECTION',
	CREATE_TOPIC_SUCCESS: 'CREATE_TOPIC_SUCCESS',
	CREATE_TOPIC_FAIL: 'CREATE_TOPIC_FAIL',
	STORE_CURRENT_TOPIC: 'STORE_CURRENT_TOPIC',

	POST_REPLY_SUCCESS: 'POST_REPLY_SUCCESS',


	GET_ALL_POST_OF_ENTRY_SUCCESS: 'GET_ALL_POST_OF_ENTRY_SUCCESS',
	GET_ALL_POST_OF_ENTRY_FAIL: 'GET_ALL_POST_OF_ENTRY_FAIL',
	// register

	CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
	CREATE_USER_FAIL: 'CREATE_USER_FAIL',
	// vote

	SUBMIT_VOTE_SUCCESS: 'SUBMIT_VOTE_SUCCESS',
	SUBMIT_VOTE_FAIL: 'SUBMIT_VOTE_FAIL',

	// quesiton

	CREATE_QUESTION_SUCCESS: 'CREATE_QUESTION_SUCCESS',
	CREATE_QUESTION_FAIL: 'CREATE_QUESTION_FAIL',

	// posting

	POST_MESSAGE_SUCCESS : 'POST_MESSAGE_SUCCESS',
	POST_MESSAGE_FAIL : 'POST_MESSAGE_FAIL',

	// logout

	LOGOUT_SUCCESS:'LOGOUT_SUCCESS',
	LOGOUT_FAIL:'LOGOUT_FAIL'


}
