
export default {
	

	// admin
	SAVEBOOK:'SAVEBOOK',
	SAVING:'SAVING',
	SAVED:'SAVED',

	// checkout
	SUBMIT_ORDER:'SUBMIT_ORDER',
	SUBMITING_ORDER:'SUBMITING_ORDER',
	SUBMITTED_ORDER:'SUBMITTED_ORDER',
	SUBMITTED_ORDER_ERROR:'SUBMITTED_ORDER_ERROR',

}
